app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [

   

   ]

mysite/urls.py
from app import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', views.home, name='home'),#13
    path('admin/', admin.site.urls),
   # path('', include('app.urls')),
    path('ule/', views.ule, name='ule'),#13
    path('signup', views.signup_page, name='signup_page'),#14
    path('login', views.login_page, name='login_page'),#14
    path('logout', views.logout_page, name='logout_page'),#14
    path('ulnowy/', views.ul_nowy, name='ul_nowy'),
    path('<int:pk>/uldetal/', views.uldetal, name='detalUl'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
]

app/templates/app/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="shortcut icon" href="#" />
    <title>Pasieka Maciej</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="icon" href="{% static 'css/ikona.png' %}" type="image/x-icon">
  </head>
  <body>
    
      <img src="{% static 'css/naglowek.png' %}" style="float: right; ">
      <img src="{% static 'css/ul.png' %}" style="float: left; ">
    

    <div class="page-header">

      <h0>Pasieka Maciej</h0>

      
        {% if request.user.is_authenticated %}
        <h1>zalogowany : {{ user.get_username }}</h1>
        {% else %}
        <h1>niezalogowany : {{ user.get_username }}</h1>
        {% endif %}

      <h2>

        {% if user.is_authenticated %}
        <a class="btn btn-danger" href="JavaScript:{document.getElementById('logout').submit()}" >Wyloguj się</a>
        {% else %}
        <a class="btn btn-warning" href="{% url 'signup_page' %}" >Zarejestruj się</a>
        <a class="btn btn-warning" href="{% url 'login_page' %}" >Zaloguj się</a>

        {% endif %}
      </h2>
      <h3>
        <a href="{% url 'home' %}"><button type="button" class="btn btn-warning" >HOME</button></a>

        <a href="{% url 'ule' %}"><button type="button" class="btn btn-warning">Ule</button></a>
        <a href="{% url 'ul_nowy' %}"><button type="button" class="btn btn-warning">Ul nowy</button></a>
        
    </div>
      </h3>


       
      {% if user.is_authenticated %}
      <form id="logout" method="POST" action="{% url 'logout_page' %}">
        {% csrf_token %}
        <input type="hidden">
      </form>
      {% endif %}
      </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    {% block content %}
    {% endblock %}
    </body>
</html>

app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}

    <div class="home">
        <h1>HOME</h1>

    </div>

{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% block content %}
  <div class="container">
    <h2>Zaloguj się</h2><br>
    {% if error %}
      <div class="alert alert-danger">
        {{ error }}<br>
      </div>
    {% endif %}
    {% if next %}
      <div class="alert alert-warning">
        {{ next }}<br>
      </div>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
      Nazwa użytkownika:<br>
      <input type="text" name="username"><br><br>
      Hasło:<br>
      <input type="password" name="password"><br><br>
      {% if nextURL %}
        <input type="hidden" name="redir" value="{{ nextURL }}">
      {% endif %}
      <input class="btn btn-primary" type="submit" value="Zaloguj">
    </form>
  </div>
{% endblock %}

app/templates/app/logout.html
{% extends 'app/base.html' %}
{% block content %}
  <div class="container">
    <h2>Wyloguj się</h2>
  </div>
{% endblock %}

app/templates/app/signup.html
{% extends 'app/base.html' %}
{% block content %}
  <div class="container">
    <h2>Zarejstruj się</h2><br>
    {% if error %}
      <div class="alert alert-danger">
        {{ error }}<br>
      </div>
    {% endif %}
    <form method="POST">
      {% csrf_token %}
      Nazwa użytkownika:<br>
      <input type="text" name="username"><br><br>
      Hasło:<br>
      <input type="password" name="password1"><br><br>
      Potwierdź hasło:<br>
      <input type="password" name="password2"><br><br>
      <input class="btn btn-primary" type="submit" value="Zarejestruj">
    </form>
  </div>
{% endblock %}

app/templates/app/ul_edit (2).html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
    <h2>Nowy ul</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Zapisz">
        </form>
</div>
{% endblock %}

app/templates/app/ul_edit.html
{% extends "app/base.html" %}

{% block content %}
    <h2>Nowy ul</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
        </form>


{% endblock %}

app/templates/app/ul_nowy.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
    <h2>Nowy ul</h2>
        <form method="POST" class="post-form">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="Zapisz">
        </form>
</div>
{% endblock %}

app/templates/app/uldetal.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
   
    
    <h1> 
        Szczegóły dla ula  "{{ uld.nazwa }}"
        <a class="btn btn-default" href="{% url 'post_edit' uld.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
    </h1>
        {% if uld %}
        
            <ul>
                <li>Data instalacji - {{ uld.install_date }}</li>
                    {% for matka in uld.matka.all %}
                <li> Matka - {{matka.matka}}</li>             
                    {% endfor %}
                <li>Data podania matki - {{ uld.matka_date }}</li>
                    {% for posiadane_ule in uld.typ_ula.all %}
                <li> Typ ula - {{posiadane_ule.typ_ula}}</li>             
                    {% endfor %}
                <li>ilość ramek - {{ uld.ilosc_ramek }}</li>
                    {% if uld.aktywny  %}
                <li>aktywny - Tak</li>
                    {% else %}    
                <li>aktywny - Nie</li>  
                    {% endif %}  
            </ul>

        {% else %}
            <p>Brak uli</p>
        {% endif %}

 </div>  


{% endblock %}

app/templates/app/ule.html
{% extends "app/base.html" %}

{% block content %}
<div class="container">
   
  
   
    <h1> Posiadane Ule </h1>
    {% if ul %}
        <ul>
            {% for uls in ul %}
                <li><a href="{% url 'detalUl' uls.id %}">{{ uls.nazwa }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <p>Brak uli</p>
    {% endif %}
</div>
{% endblock %}

app/templates/app/ule2.html
{% extends "app/base.html" %}

{% block content %}
   
    <h1> Posiadane Ule test </h1>
    {% if ul %}
        <ul>
            {% for posiadane_ule in ul %}
                <li><a href="{% url 'app:detalUl' posiadane_ule.id %}">{{ posiadane_ule.nazwa }}</a></li>
            {% endfor %}
        </ul>

    {% else %}
        <p>Brak uli</p>
    {% endif %}
{% endblock %}